site:
  title: Rashidi Zin
  url: https://rashidi.zin.my

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: ./ui
    snapshot: true

output:
  dir: ./build/site
